### ISSUE TITLE
Eng doc writing 3/22 [DOW tracking issue]

### ISSUE THREAD

**Issue by bion** [civiform/civiform#2133]
Tracking issue for DOW SWEs contributing to doc writing March, 2022.

Documentation tasks:

- [x] versioning system @shanemc-goog 
- [ ] database transactionality @shanemc-goog 
- [x] deployment repo, deployment templating system @bion

**Comment by shanemc-goog** [comment]
Versioning at https://github.com/seattle-uat/civiform/wiki/Data-versioning-model
