### ISSUE TITLE
Security checklist for deploy

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#2690]
Complete this prior to launch. To be expanded as needed:

Database:
- [x] Database is not accessible from the internet
- [ ] Only Apprunner has access 

File storage for Civiform:
- [x] No public access
- [x] Only Apprunner service role can access
- [x] Files are encrypted
- [x] (Maybe) Break glass functionality for the admin?

Logs and TF state:
- [ ] No public access
- [ ] Only admin role can access
- [ ] Files are encrypted

Apprunner service:
- [ ] Only admin role can make modifications

Load balancing:
- [x]  Don't use default SSL Policy. Prefer ELBSecurityPolicy-FS-1-2-Res-2020-10

Secrets:
- [ ] Only admin role and apprunner role have access to secrets
- [x] Secrets are not visible in TF state

Authentication:
- [ ] Make sure it grants intended access  
- [ ] Make sure applicants can't sign in as admin

**Comment by jessbumblebee** [comment]
Hi Bion, do you know what the status of this issue is by any chance? 
As the deploy system was launched, can this be closed or are there follow ups you are aware of?

**Comment by bion** [comment]
@jessbumblebee I think this can be closed, but it's a good reminder to look through the deploy system to double check we're following the security practices mentioned
