### ISSUE TITLE
Oncall: 2022-10-12

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3667]
(Test for a temple)

Resources:

- [Oncall Guide](https://docs.civiform.us/governance-and-management/project-management/on-call-guide#on-call-responsibilities)
- [Release Guide](https://docs.civiform.us/contributor-guide/developer-guide/releasing)

# Task list:

- [ ] Create an Oncall issue for the next person
- [ ] Check Security lists daily
- [ ] Check Dependency updates once

## Release
- [ ] Create a Draft Release by 12 PT

- [ ] Contact Matthew Sprenke for QA.

- [ ]

**Comment by shanemc-goog** [comment]
@bion How's this look for a template?

**Comment by shanemc-goog** [comment]
Security Issue #3674 found
