### ISSUE TITLE
Oncall: 2022-10-19

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3676]
The Oncall is responsible for releasing a new version of CiviForm at the start of their rotation and general upkeep through their rotation.  This is an aid for each rotation, but the docs are the source of truth.

Rotations begin each Wednesday.

Please check off all items at their appropriate times during your rotation.

Resources:

- [Oncall Guide](https://docs.civiform.us/governance-and-management/project-management/on-call-guide#on-call-responsibilities)
- [Release Guide](https://docs.civiform.us/contributor-guide/developer-guide/releasing)

# Task list:

## Release
- [x] Create a Draft Release by 12 PT Wed
- [x] Contact Matthew Sprenke for QA on Slack
- [x] If Matthew is unavailable have the general team attempt a best-effort QA.
- [x] After QA, publish the release
- [x] Email release notes

## General 
- [x] Create an Oncall issue for the next rotation
- [x] Check Security lists daily
- [x] Check Dependency updates once

**Comment by shanemc-goog** [comment]
Please create the new oncall rotation tracker.  There's an Issue template now

**Comment by nbeloglazov** [comment]
Done: https://github.com/civiform/civiform/issues/3722
