### ISSUE TITLE
Tracking: Eligibility conditions for programs

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3744]
Tracking issue for adding Eligibility checking to programs.

The basic approach will be to mimic the Show/Hide system and re-use the Predicate logic backend flows and data storage.

This does not include the feature flag being removed (that is tracked [here](https://github.com/civiform/civiform/issues/4605)).

[Design Doc](https://docs.google.com/document/d/1A7ftdnAOghd2BCohNRtppyRpB4oKkik_0zAal4yUcuk/edit#heading=h.fvf1dku1q5pk) 

## Predicate logic system
 
- [x] Support and/or operations #3743 
- [x] Storage for Eligibility Predicates #3922
- [x] Feature Flag #3923

## Admin Flows
- [x] -- Evaluate eligibility questions #3926
- [x] -- Add/Remove eligibility #3932 
- [x] -- Restrict Eligibility available questions to the block #4025 
- [x] -- Show eligibility in Application view #4079

## Applicant Flows 
- [x] -- Evaluate eligibility upon submit #4080
- [x] -- Cleanup IneligibleBlockView #4083
- [x] -- Show status in preview/review page #4002 
- [x] -- Show not eligible banner on pre-view page #4141
- [x] -- Show status on program list for in-progress application #4142

## Trusted Intermediary Flows 
- [x] -- Ensure correct text shows for trusted intermediaries #4184

## Custom logic
- [x] Fix Currency Predicates #3854

## Other
- [x] Add translations #4127
- [x] #4315

**Comment by bion** [comment]
@dkatzz can this issue be closed?

**Comment by dkatzz** [comment]
> @dkatzz can this issue be closed?

The only open item is enabling the flag, but everything else has been completed. Happy to separate that out since its separate from the work?
