### ISSUE TITLE
Oncall: 2022-12-21

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3941]
The Oncall is responsible for releasing a new version of CiviForm at the start of their rotation and general upkeep through their rotation. This is an aid for each rotation, but the docs are the source of truth.

Rotations begin each Wednesday.

Please check off all items at their appropriate times during your rotation.

Resources:

- [Oncall Guide](https://docs.civiform.us/governance-and-management/project-management/on-call-guide#on-call-responsibilities)
- [Release Guide](https://docs.civiform.us/contributor-guide/developer-guide/releasing)

# Task list:

## General

- [x] Create an Oncall issue for the next rotation
- [ ] Check Security lists daily
- [ ] Check #ci Slack channel daily to monitor failed pushes
- [ ] Check Dependency updates once

**Comment by shanemc-goog** [comment]
NOTE: We are not doing a release this cycle due to the US holidays.
