### ISSUE TITLE
Oncall: 2023-01-03

### ISSUE THREAD

**Issue by nbeloglazov** [civiform/civiform#3998]
The Oncall is responsible for releasing a new version of CiviForm at the start of their rotation and general upkeep through their rotation. This is an aid for each rotation, but the docs are the source of truth.

Rotations begin each Wednesday.

Please check off all items at their appropriate times during your rotation.

Resources:

- [Oncall Guide](https://docs.civiform.us/governance-and-management/project-management/on-call-guide#on-call-responsibilities)
- [Release Guide](https://docs.civiform.us/contributor-guide/developer-guide/releasing)

# Task list:

## Release

- [x] Create a Draft Release by 12 PT Wed
- [x] Contact Matthew Sprenke for QA on Slack
- [ ] If Matthew is unavailable have the general team attempt a best-effort QA.
- [ ] After QA, publish the release
- [ ] Email release notes

## General

- [ ] Create an Oncall issue for the next rotation
- [ ] Check Security lists daily
- [x] Check #ci Slack channel daily to monitor failed pushes
- [x] Check Dependency updates once

**Comment by bion** [comment]
Release blocked on an error encountered in Seattle staging. Discussion on slack: https://app.slack.com/client/T01Q6PJQAES/C046D5BPVJ9/thread/C046D5BPVJ9-1672867412.203549
