### ISSUE TITLE
Tracking: Seattle FreshBucks launch

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#4026]
Eng tracking for the FreshBucks launch:

- [ ] General Eligibility support #3744
- [x] Multiple Question Predicates #3950 
- [ ] Address #4051 
- [x] ---- Connection to Predicate system #4028

**Comment by shanemc-goog** [comment]
@seanmalbert can you make a Issue/tracking-Issue/Pr for the address stuff and link it above please

**Comment by bion** [comment]
No longer tracked here.
