### ISSUE TITLE
Automatically add server variables that are covered in in env-var docs to the variables that can be passed from the deploy system to the server.

### ISSUE THREAD

**Issue by jessbumblebee** [civiform/civiform#4612]
This issue covers remaining tasks that are needed for the completion of https://github.com/civiform/cloud-deploy-infra/pull/132

Here is a breakdown of remaining work: 
https://docs.google.com/document/d/1sM161Y8jZRw4UhZai9c_XjylN7y_yr9yONO914byYko/edit#

Remaining Tasks:
- [x] Fix and merge https://github.com/civiform/cloud-deploy-infra/pull/132 https://github.com/civiform/cloud-deploy-infra/pull/180
- [x] Fix and merge https://github.com/civiform/cloud-deploy-infra/pull/147
- [x] Enable downloading correct version of `env-var-docs.json` and `env-var-docs.parser` https://github.com/civiform/cloud-deploy-infra/pull/154 https://github.com/civiform/cloud-deploy-infra/pull/183 https://github.com/civiform/cloud-deploy-infra/pull/184
- [x] Look at spreadsheet and resolve unknown variables 
- [x] Figure out var validation (leaving off validation of index-list type for now because we don't support sub-typing) https://github.com/civiform/civiform/pull/4992 https://github.com/civiform/civiform/pull/4999
- [x] Sync staging deploy code up with standard deploy code https://github.com/civiform/civiform-staging-deploy/pull/49 https://github.com/civiform/civiform-staging-deploy/pull/55 
- [x] Test on AWS staging https://github.com/civiform/civiform-staging-deploy/pull/56 https://github.com/civiform/cloud-deploy-infra/pull/194
- [x] Figure out issue with version of `env-var-docs.json` and parser package -- "latest" should be latest docker image, not latest release https://github.com/civiform/cloud-deploy-infra/pull/203
- [x] Make sure we can still pass in specific snapshot tags https://github.com/civiform/civiform-deploy/pull/42 https://github.com/civiform/cloud-deploy-infra/pull/203
- [x] Figure out issue with required vars (all required vars are now required for all deployments, even if they're not used in that deployment) https://github.com/civiform/civiform/pull/5093 https://github.com/civiform/civiform/issues/5092
- [x] Fix blocker with python versioning for AR https://github.com/civiform/civiform/pull/5298
- [x] Enable for other deployments https://github.com/civiform/cloud-deploy-infra/pull/185 https://github.com/civiform/cloud-deploy-infra/pull/211 https://github.com/civiform/civiform/issues/5244 https://github.com/civiform/cloud-deploy-infra/pull/220
- [x] Fix naming inconsistencies (want server vars and config vars to have matching names) https://github.com/civiform/civiform/issues/5245
- [x] Add "required" back in to duplicate vars in `env-var-docs.json` https://github.com/civiform/civiform/issues/5247
- [x] Figure out what to do for vars that are used in the server and in the deploy system
- [x] Cleanup - delete vars from `cloud-deploy-infra` that are now being read directly (for AWS and then separately for Azure) https://github.com/civiform/civiform/issues/5249
- [x] Update documentation and config files (autogenerate?) https://github.com/civiform/civiform/issues/5250
