### ISSUE TITLE
Migrating Seattle To Terraform Deployment

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4687]
Tracking task to manage child tasks

- [x] https://github.com/civiform/civiform/issues/4684
- [x] https://github.com/civiform/civiform/issues/4683
- [x] https://github.com/civiform/civiform/issues/4676
- [x] https://github.com/civiform/civiform/issues/4675
- [x] Migrate Seattle staging to TF Deploy System
- [x] Create new Seattle prod environment to TF Deploy System
- [x] Migrate Seattle prod to new environment

**Comment by elisekalstad** [comment]
Change failed, rolled back to original instance. Investigating cause of failure before trying again.

**Comment by gwendolyngoetz** [comment]
Cause is auth related environment variable config issue.
