### ISSUE TITLE
[Q2 Epic] Improve deployability

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#4760]
### Epic Overview:
New CiviForm deployments experience churn with server configuration involving communication loops between administrators, civic IT staff, and CiviForm maintainers. Through the work in this epic, we would like to improve the experience and confidence with which civic staff are able to set up a new deployment and administer existing deployments. 

### Goal:
Increase the ease and reliability of setting up and deploying CiviForm environments.

### Key Deliverables:
- [x] Automate passing server vars through the deployment system 
- [x] Build a settings UI that allows admin to control some server configuration variables
- [x] Implement ability to pass list type vars through deployment system (need this for setting a subset of languages)
- [x] Make `bin/setup` script idempotent so can run it multiple times without running into the issue where things are partially setup

### Documentation:
[PRD for Settings UI](https://docs.google.com/document/d/1QV0hT6yi4D6DQkkVniMo6aqT4aqVIfopvhI8rn9yFZI/edit#heading=h.x9snb54sjlu9)
[TDD for Settings UI](https://docs.google.com/document/d/1FK5YLJd6jVu1O1uuu2OOR2mXTs3yVEXkzyfjVwnkz8s/edit#)

[TDD for automating server vars](https://docs.google.com/document/d/1sM161Y8jZRw4UhZai9c_XjylN7y_yr9yONO914byYko/edit)
[Tracking issue for automating server vars](https://github.com/civiform/civiform/issues/4612)

**Comment by rockycodes** [comment]
All of the key deliverables for this epic are completed so I am closing this issue. We can reopen if necessary.
