### ISSUE TITLE
[Ongoing Epic] Component Library Discovery

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#4761]
### Epic Overview:
Currently there is no documentation around existing visual styles and components in CiviForm. This makes it hard for new engineers, designers, and product managers to design and implement new features that are in line with existing components. This epic is focused on creating a longer term plan to address this issue through research and discovery. A part of this work will be improving documentation for collaboration between CiviForm maintainers.

### Goal(s):
The goal of this epic is to lay the groundwork for creating a consistent look and feel across CiviForm. 

### Key Deliverables:
- [ ] Create a page in staging (hidden page at `dev/components`) that displays all existing components
- [ ] Explore options for a longer term plan for a more robust component library (eg. using Bloom's library or creating our own)
- [x] Create a V1 style guide with atom level pieces
- [x] Complete interface audit and findings workshop with Exygy CiviForm team
 

### Documentation:
To come

**Comment by melanie-exygy** [comment]
We have since adopted the USWDS component library and are using Figma to mock any components which aren't in USWDS
