### ISSUE TITLE
Oncall: 2023-06-05

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#5015]
The Oncall is responsible for releasing a new version of CiviForm on Wednesday during their rotation and general upkeep through their rotation. This is an aid for each rotation, but the docs are the source of truth.

Rotations begin each Monday, with the release happening on Wednesday.

Please check off all items at their appropriate times during your rotation.

Resources:

- [Oncall Guide](https://docs.civiform.us/governance-and-management/project-management/on-call-guide#on-call-responsibilities)
- [Release Guide](https://docs.civiform.us/contributor-guide/developer-guide/releasing)

# Task list:

## Release

- [x] Create a Draft Release by 12 PT Wed
- [x] Contact Matthew Sprenke for QA on Slack
- [ ] If Matthew is unavailable have the general team attempt a best-effort QA.
- [x] After QA, publish the release
- [x] Email release notes

## General

- [ ] Create an Oncall issue for the next rotation
- [x] Check Security lists daily
- [x] Check #ci Slack channel daily to monitor failed pushes
- [x] Check Dependency updates once

**Comment by dkatzz** [comment]
Play framework posted about a couple of vulnerabilities later last week (https://groups.google.com/g/play-framework-security/c/vU1AugoBe8s):
- CVE-2022-31018 - Denial of service when binding forms from JSON (affecting Play versions 2.8.3-2.8.15) - https://github.com/playframework/playframework/security/advisories/GHSA-v8x6-59g4-5g3w - Even though we use Form.bindFromRequest, I don't think we should be impacted, since we're not parsing a request body of type application/json. The impact would be OOM errors, so it may be good to double check for this in the logs
- CVE-2022-31023 - Dev error stack trace leaking into prod (affecting Play versions up to and including 2.8.15) - https://github.com/playframework/playframework/security/advisories/GHSA-p9p4-97g9-wcrh - I don't think this should impact us either since we don't use the CORSFilter or CORSActionBuilder use the static object DefaultHttpErrorHandler

Added to slack so others are aware.
