### ISSUE TITLE
API Generated Docs

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#5262]
API Generated Docs intend to clearly document what API consumers can expect the response for a given program to look like for the `/applications` endpoint.

[Design document](https://docs.google.com/document/d/1mv6YTk0-Pt9ygLsZHEHu2RXqkzO3sIyAJ7VCl6Vz-v0/edit?resourcekey=0-GnlC2ufUkH7QtM8i1O_p1A#heading=h.xf9qz34jakum)

Sub-issues:
* #4872
* #4945
* #4946

#5253 is the initial PR. It adds API docs gated under the flag `api_generated_docs_enabled`.

TODO after that PR:
- [x] Consider implementing Sijia's frontend suggestions ([mock](https://github.com/civiform/civiform/assets/30369272/f875d0f0-334d-429f-ab11-6834dd3535dd) of some of these)
   - Can wrap columns if need more than 3 columns
   - Can remove "Question" from "Question text" etc
   - For lower underscore names, we can keep the font consistent, don't need to use monospace
   - Bigger size and bold for name of question
   - Add accordion for the help text at the top of the API docs page
   - Implemented in #5284
- [x] Add other fields outside of `application` to the API Response Preview
   - Implemented in #5294 and #5297
- [x] Support draft programs (#4945)
   - Implemented in #5310
- [ ] Add copy near selectable options (maybe a tooltip) that makes it clear that the names of options may change/have changed, without changing users' selections. That is, the text of their selection may not match what they saw when they applied, only the ID of the selection is consistent. (#5350)
- [ ] Add "Published time" and "Removed time" field to each question to make it clear when that question was published or removed from each program (so API consumers understand that it won't be on applications earlier/later than those time). ([Design doc link](https://docs.google.com/document/d/1mv6YTk0-Pt9ygLsZHEHu2RXqkzO3sIyAJ7VCl6Vz-v0/edit?resourcekey=0-GnlC2ufUkH7QtM8i1O_p1A#bookmark=id.5eu7swcmtuym)) (#5351)
- [ ] Support enumerated questions (already in API, need to add to API docs) (#5238)
- [ ] Support enumerator questions (not in API nor API docs) (#4975)
- [ ] Support opening the API docs link in a new browser (i.e. incognito mode). Currently, opening the CiviForm home page in incognito, unauthenticated, followed by opening the API docs page (without logging in as an admin) **works**, but opening the API docs page in incognito mode directly does not work. (#5353)
- [ ] Golden Diff Test ([Design doc link](https://docs.google.com/document/d/1mv6YTk0-Pt9ygLsZHEHu2RXqkzO3sIyAJ7VCl6Vz-v0/edit?resourcekey=0-GnlC2ufUkH7QtM8i1O_p1A#heading=h.l97rdqft47cj)) (#5354)
- [ ] OpenAPI spec (stretch goal) (#4946)

**Comment by avaleske** [comment]
issues have been created for each of these tasks, so I'm closing this as a duplicate.
