### ISSUE TITLE
[Epic] CiviForm Design Refresh and Standardization

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5397]
### Checklist (remove this section after completion)

- [ ] Create a new Epic label in the Civiform project that matches the name of this issue
- [ ] Under the project, set `Epics` to the epic label you created
- [ ] Under the project, set `Quarter` to the quarter this epic is slated for

### Epic Overview

Our current CiviForm design is not consistent and does not always follow best practices.  In this epic, we will re-write styles and markup so that they follow our new [style guide](https://zeroheight.com/4ab70b9e3/p/41ac7a-civiform-design-system), are consistent and follow industry standards.  

### Goal

To improve the clarity and consistency of the CiviForm experience.  Also, this work will have the added benefit of making our application more accessible in that it will be more friendly to assistive technology. 

### Key Deliverables

For desktop:  

1. Define our design refresh approach:  [#5538](https://github.com/civiform/civiform/issues/5538)
2. Standardize typography (size, weights, fonts) according to the style guide.  [#5406](https://github.com/civiform/civiform/issues/5406)
3. Make sure the markup is well-formed.  [#5407](https://github.com/civiform/civiform/issues/5407)
4. Follow colors from the style guide.  [#5408](https://github.com/civiform/civiform/issues/5408)
5. Make our design tokens configurable by civic entities.  [#5410](https://github.com/civiform/civiform/issues/5410)
6. Standardize button styling.  [#5436](https://github.com/civiform/civiform/issues/5436)

For mobile:

7. Implement any mobile-specific styles.

### Documentation

_PRD placeholder_
_Mocks placeholder_
_TDD placeholder_

**Comment by melanie-exygy** [comment]
@isabelcshaw As we discussed in our last Sprint Planning meeting, the latest plan for the design refresh is to skip over creating a page that displays all our existing components (see the 1st deliverable here:  [4761](https://github.com/civiform/civiform/issues/4761) and go straight to standardizing our styles.  @sijiayam and I discussed a plan for this and came up with the steps listed in this epic.  

There are a few steps in the checklist above which I thought best that I leave to you.  For example, creating the epic label and assigning it to a quarter.

Also, I think a PRD and TDD may not be needed for most of this work, other than for the style tokenization.  Some mocks might be nice, however.
