### ISSUE TITLE
[Epic] Universal Questions

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#5500]
### Checklist (remove this section after completion)

- [x] Create a new Epic label in the Civiform project that matches the name of this issue
- [x] Add this issue to the `CiviForm Project Roadmap & Tracker` project
- [x] Set the status of this issue to `Needs Scoping` if PRDs/Mocks/TDD are not ready
- [x] Under the project, set the `Initiative` this epic is tied to
- [x] Under the project, set `Epics` to thie epic label you created
- [x] Under the project, set `Quarter` to the quarter this epic is slated for

### Epic Overview

The goal for this set of features is to allow CiviForm admins to mark a certain set of questions as "Universal", showing them prominently as such in the UI, and prompt the admin if they haven't used all of the universal questions in their program. 

### Key Deliverables

- Universal questions feature
- Email applicants based on answer to actionable email question, if available
- Use answer to actionable name question for program application view rather than application ID or pre-seeded name question
- Filter applications based on email, name, phone number answers

### Documentation

[Universal Questions PRD](https://docs.google.com/document/d/1ujrHD5Na8EcosN1UQ6f5MxYtopeCasBgvZ812nsO59Y/edit)
[Universal Questions TDD](https://docs.google.com/document/d/1-2stuFeIKWkiDCHZlnytsG8c0q0G_Dl3dnplSY4Wy5E/edit)
[Mocks](https://www.figma.com/file/KqfHZYPS3Ffd93aJsfkNYZ/Universal-Questions?type=design&node-id=293-1092&mode=design&t=mGC8OAmup0UNw6Gw-0)
