### ISSUE TITLE
[Epic] Primary Applicant Information (Actionable) Questions

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#5808]
### Checklist (remove this section after completion)

- [x] Create a new Epic label in the Civiform project that matches the name of this issue
- [x] Add this issue to the `CiviForm Project Roadmap & Tracker` project
- [x] Set the status of this issue to `Needs Scoping` if PRDs/Mocks/TDD are not ready
- [x] Under the project, set the `Initiative` this epic is tied to
- [x] Under the project, set `Epics` to thie epic label you created
- [x] Under the project, set `Quarter` to the quarter this epic is slated for

### Epic Overview

The goal for this set of features is to allow admins to mark certain questions as "primary applicant information" so that CiviForm can take actions based on the answers to these particular universal questions in a program, such as emailing a guest applicant without an email address attached to their account.

### Documentation

[Actionable Questions PRD](https://docs.google.com/document/d/1qutDkMPG25ZJszchUpaMn7mxJ-gdiL7fCWzeUcdEtxU/edit?resourcekey=0-BSOhVAxL5xcYShp2zXh57A)
[Primary Applicant Info TDD](https://docs.google.com/document/d/13xTLRl82gDD0VajM68gVdOGUV6alXi_mtluf1uUT1Lo/edit)
[System Actions for Primary Applicant Info TDD](https://docs.google.com/document/d/10coGz5wuCGyulfM4y7J5vXaKpoH8hAulqVJcevYGpnc/edit#heading=h.bknox3ib8wpb)
