### ISSUE TITLE
[North Star Applicant UI] Ensure text questions respect min and max response lengths and don't submit on enter

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#6943]
#### Describe the solution presented in this issue.
Text questions can have a min and max number of characters. We need to make verify we enforce those properly. Our existing text input doesn't submit when the user hits enter within the text field, and we want to mimic that functionality

#### Done when:
What criteria need to be met for the issue to be finished? 
- [x] Cannot submit a response with fewer than the minimum characters
- [x] Cannot submit a response with more than the max characters
- [x] Don't submit the form on hitting enter within the input
