### ISSUE TITLE
[North Star Applicant UI] Render File Upload Questions

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#6959]
#### Describe the solution presented in this issue.
Implement file upload questions in Thymeleaf. This is likely going to be more complex than most other questions, since there is more UI involved

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] Users can see and respond to file upload questions
- [ ] Add logic to show already uploaded file
- [ ] Ensure user is properly redirected after submitting
- [ ] Accept the correct mime types of file
- [ ] Allow skipping or deleting an already uploaded file

**Comment by greg-hyde** [comment]
This is a duplicate of https://github.com/civiform/civiform/issues/6926 so closing
