### ISSUE TITLE
Design specs for checkbox question type

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#7168]
## Description
Design specs for our checkbox question type that include USWDS component/styles and spacing guidelines. These designs will depict how the checkbox question type renders on desktop, mobile and other responsive screen types. This is a part of the thymeleaf/htmx front end overhaul work. 

### Current implementation:
[Checkbox - standard screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/checkbox_test/checkbox-north-star.png)
[Checkbox - medium screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/checkbox_test/checkbox-north-star-medium.png)
[Checkbox - mobile screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/checkbox_test/checkbox-north-star-mobile.png)
[Checkbox - standard screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/checkbox_test/checkbox-errors-north-star.png)
[Checkbox - medium screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/checkbox_test/checkbox-errors-north-star-medium.png)
[Checkbox - mobile screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/checkbox_test/checkbox-errors-north-star-mobile.png)

## Requirements:
- [ ] Responsive screen sizes (mobile, medium, standard)
- [ ] Padding and spacing guidelines
- [ ] Max and min width
- [ ] Error states for different screen types

## Figma links:
- [Checkbox question type](https://www.figma.com/file/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?type=design&node-id=1865%3A2727&mode=dev&t=5RYMWgbSpL79zCvJ-1)
