### ISSUE TITLE
Design specs for radio button question type

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#7169]
## Description
Design specs for our radio question type that include USWDS component/styles and spacing guidelines. These designs will depict how the radio question type renders on desktop, mobile and other responsive screen types. This is a part of the thymeleaf/htmx front end overhaul work. 

### Current implementation:
[Radio question- standard screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/radio_button_test/radio-button-north-star.png)
[Radio question - medium screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/radio_button_test/radio-button-north-star-medium.png)
[Radio question - mobile screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/radio_button_test/radio-button-north-star-mobile.png)
[Radio question - standard screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/radio_button_test/radio-button-errors-north-star.png)
[Radio question - medium screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/radio_button_test/radio-button-errors-north-star-medium.png)
[Radio question - mobile screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/radio_button_test/radio-button-errors-north-star-mobile.png)

## Requirements:
- [ ] Responsive screen sizes (mobile, medium, standard)
- [ ] Padding and spacing guidelines
- [ ] Max and min width
- [ ] Error states for different screen types

## Figma links:
- [Radio question type](https://www.figma.com/file/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?type=design&node-id=1890%3A3285&mode=dev&t=5RYMWgbSpL79zCvJ-1)

## Notes:
- Max width: 480px

**Comment by sijiayam** [comment]
@greg-hyde I've added initial figma links. Please let me know if you have questions about any of the design specs.
