### ISSUE TITLE
Design specs for text input question type

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#7172]
## Description
Design specs for our text input type that include USWDS component/styles and spacing guidelines. These designs will depict how the text input question type renders on desktop, mobile and other responsive screen types. This is a part of the thymeleaf/htmx front end overhaul work. 

### Current implementation:
[Text question- standard screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/text_test/text-north-star.png)
[Text question - medium screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/text_test/text-north-star-medium.png)
[Text question - mobile screen](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/text_test/text-north-star-mobile.png)
[Text question - standard screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/text_test/text-errors-north-star.png)
[Text question - medium screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/text_test/text-errors-north-star-medium.png)
[Text question - mobile screen, error state](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/text_test/text-errors-north-star-mobile.png)

## Requirements:
- [ ] Responsive screen sizes (mobile, medium, standard)
- [ ] Padding and spacing guidelines
- [ ] Max and min width
- [ ] Error states for different screen types

## Figma links:
- [Text input question type](https://www.figma.com/file/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?type=design&node-id=1865%3A3050&mode=dev&t=5RYMWgbSpL79zCvJ-1)
- [error state](https://www.figma.com/file/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?type=design&node-id=1923%3A9596&mode=dev&t=5RYMWgbSpL79zCvJ-1)

**Comment by sijiayam** [comment]
@greg-hyde I've added initial figma links. Please let me know if you have questions about any of the design specs.
