### ISSUE TITLE
Azure Work Plan Document

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#7646]
#### Problem Statement:

Create a document to plan and prioritize the high level work around building Azure support. 

#### Solution:

General plan of azure work to be done

#### Link to TDD:

https://docs.google.com/document/d/1wbKpcm9AJXim6MAvX9g23sJzKnYMquMySESPXgHO2Ck/edit

#### Checklist (remove this section after completion)

- [ ] Link the PRD or TDD above. For TDDs, link the associated PRD as well.
- [ ] Remove the PRD label if this is a TDD, vice versa if this is a PRD.
- [ ] In the project, set `Epics` to the epic label for this feature
- [ ] In the project, set `Initiative` to the correct initiative label for the overarching initiative this feature belongs to
- [ ] In the project, set `Status` to the current status of the PRD / TDD. `In progress` if you're drafting, `Needs review` if it is ready for review or in the process of review, `Done` if the document is finalized.
- [ ] In the project, set `Quarter` to the quarter this PRD / TDD is being worked on

#### Additional Context:

Any additional context to be added here.
