### ISSUE TITLE
[North Star Applicant UI] Allow residents to filter programs by category on the homepage

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#7813]
#### Describe the solution presented in this issue.
Migrate program filtering functionality into Thymeleaf.  This issue is for functionality only, not styling.

#### Add screenshot of relevant mocks for this issue here: 
![Image](https://github.com/user-attachments/assets/06ca970b-5e62-4dd6-8ed6-4979284a27a9)

#### Additional Context
[TDD](https://docs.google.com/document/d/1hNL6r1JdauL5xjGRIw1dlDD3m81h9g0vUSiqlXOGDCs/edit?usp=sharing)
As of 10/28/24, as agreed upon by UX/Product, we'll be adding two buttons to the filter form, on button to apply filters and one to clear them.  This will mean that we won't have to re-render the page after each filter click.
After applying filters, we should scroll to the top of the "Programs based on your selections" section.

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] With the North Star enabled, residents can filter programs by category on the homepage
- [ ] Filtered programs appear in a "Programs based on your selections" section and all others appear in a section entitled "Other programs and services"
- [ ] Both sections show a count next to the header
- [ ] There is no flickering
