### ISSUE TITLE
[North Star Applicant UI] Create the “My Applications” section on the homepage

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#7814]
#### Describe the solution presented in this issue.
Migrate the My Applications section of the homepage to Thymeleaf.  This section will hold programs that the resident has applied to or has started applying to.  This issue does not include styling.

#### Additional Context
[TDD](https://docs.google.com/document/d/1hNL6r1JdauL5xjGRIw1dlDD3m81h9g0vUSiqlXOGDCs/edit?usp=sharing)

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] The “In progress” or “Submitted” sections are combined into one "My Applications" section
- [ ] There is a count next to the header
- [ ] The cards in this section don't include images or category tags.
- [ ] The "My applications" section should be above the common intake form if there is one.

**Comment by sijiayam** [comment]
@melanie-exygy Is this issue a duplicate to this story? https://github.com/orgs/civiform/projects/1/views/94?pane=issue&itemId=70363606

**Comment by melanie-exygy** [comment]
> @melanie-exygy Is this issue a duplicate to this story? https://github.com/orgs/civiform/projects/1/views/94?pane=issue&itemId=70363606

I think the other story is just for the styling portion of this.  I'll close the other issue since it doesn't have many details and will update this one.
