### ISSUE TITLE
Mocks for "Review" page

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#7935]
# Design updates
#### Page layout:
- Page header
- Progress bar
- Main content, review sections by screens
- Action buttons

#### Page header updates
- [ ] Update text and color styles
#### Page header updates
- [ ] Should follow the same format as all other form pages
#### Main content
- [ ] Review sections are laid out in order by screen
- [ ] Each screen section has:
  - [ ] Screen title
  - [ ] #8780
  - [ ] Question titles and responses are shown in order of question
#### Action buttons
- [ ] Save and exit
  - [ ] If an applicant is logged in, they will redirected to a page with a success message
  - [ ] #8779
- [ ] Submit application
  - [ ] If an applicant submits their application, they will be redirected to the confirmation screen

### Spacing guidelines

- Refer to Figma devmode annotations to see the spacing guidelines
- CiviForm spacing documentation
- For more information about our spacing guidelines, see our writeup on spacing

### Layout guidelines
- [Layout guidelines](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4287-23350&t=XCIBJDfrfoPaX0e8-1)
- Designs include
  - [ ] [Mobile layout](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3707-15814&t=XCIBJDfrfoPaX0e8-1)
  - [ ] [Desktop layout](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2468-5090&t=XCIBJDfrfoPaX0e8-1)

### Color guidelines
- [USWDS theme color tokens](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)
  - All colors used in the application should use one of the USWDS theme tokens
  - Dark text should use always use the theme token `ink`
  - View designs for more details

### Text styles
- All text should use the class `usa-prose` unless specified otherwise 
- https://designsystem.digital.gov/components/prose/

### USWDS components used

- [USWDS step indicator component](https://designsystem.digital.gov/components/step-indicator/) 
    - Guidance on the how to use the component
    - We are using the variant `.usa-step-indicator--no-labels`
    - See other North Star form page for styles implemented
- [USWDS button](https://designsystem.digital.gov/components/button/)
    - We are using the default and `outline` variant
    - See guidance in devmode

### Accessibility
- TBD

### Preview mock
<img width="307" alt="image" src="https://github.com/user-attachments/assets/604497d4-4f99-400d-b87f-8db451253819">

**Comment by ssandbekkhaug** [comment]
I think this is also known as the "Program Summary" page

![Image](https://github.com/civiform/civiform/assets/23390490/e6ca4465-d960-47ec-b16d-9e792333e27c)

**Comment by sijiayam** [comment]
@ssandbekkhaug Feel free to review to see if there are any other design requirements/specs you may need. 

I can copy the requirements to the engineering styling story if it looks good.

**Comment by ssandbekkhaug** [comment]
Thank you for the detailed writeup! A few clarifying questions:

1. "If an applicant is logged in, they will redirected to a page with a success message" 
     - What does the success message look like? Is it a new page? Is it a toast on the home page? What's the copy?
3. When the applicant clicks "Submit", and there's an error, what should happen?
4. The image file name looks like a link. What happens when the user clicks it?

**Comment by sijiayam** [comment]
@ssandbekkhaug 
1. Confirmed with @isabelcshaw today. If an applicant is logged in they will be redirected to the homepage, no success message needs to be shown. A program card with an in progress tag should display in their my applications section.
2. How do we currently handle this error?
3. The file should download, this is feature parity. I believe this is current functionality.

**Comment by ssandbekkhaug** [comment]
Thank you!

2. In the legacy UI, we show this page. Should we show an equivalent page in North Star?

<img width="1308" alt="Screenshot 2024-10-09 at 3 33 39 PM" src="https://github.com/user-attachments/assets/54aaf0d3-0ea1-4e1a-bfe2-038551becb08">

**Comment by sijiayam** [comment]
I believe we can use this page and its styling. Does this mean we need to implement an error page in thymeleaf/open an issue for that?

cc @isabelcshaw @shreyachatterjee00 any thoughts on this? How we display an error for users when they submit an application?

**Comment by sijiayam** [comment]
@ssandbekkhaug Any thoughts on the above? Are we okay to close this issue?

**Comment by ssandbekkhaug** [comment]
Yes, we can close this issue. I filed new issues for the error page:

- https://github.com/civiform/civiform/issues/8873
- https://github.com/civiform/civiform/issues/8874
- https://github.com/civiform/civiform/issues/8875
