### ISSUE TITLE
[North Star Applicant UI] Add domain info to footer

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7959]
Mocks show "domain.gov" and some extra content in the footer that we don't have access to 
![9kzGb8bcNV8Enwq](https://github.com/civiform/civiform/assets/156004543/6c54dda0-aba6-41d9-adcf-0e2389d20f34)

So for now our footer shows this
![962nFj3WfCF9o4d](https://github.com/civiform/civiform/assets/156004543/f25649da-6c72-4daa-85f6-63efc03b9f03)

This bug tracks adding the necessary info. It depends exactly what content we decide to add how much plumbing we'll need to add

**Comment by greg-hyde** [comment]
This could be a P0 or P1

**Comment by ssandbekkhaug** [comment]
- The URL for the civic entity can be found by calling this method:
```public Optional<String> getCommonIntakeMoreResourcesLinkHref(RequestHeader request)```
- This part of the HTML code controls the footer: https://github.com/civiform/civiform/blob/d29bac8dc3692c4cb3e770bace5996bbc1176a16/server/app/views/applicant/NavigationFragment.html#L263

This issue is done when ALL of the following are true:

- [ ] The footer shows the URL of the civic entity's website
- [ ] The footer shows "Looking for more information or services? Visit cityorcounty.gov" (replace "cityorcounty.gov" with the actual URL)
- [ ] Text is styled appropirately using CSS
- [ ] Hyperlink(s) are styled appropriately using CSS

**Comment by ssandbekkhaug** [comment]
@erikang20 Here's another good starter issue

**Comment by lucashurt** [comment]
Hello, can i be assigned this issue? i believe i can get it fixed while satisfying the requirements,

**Comment by melanie-exygy** [comment]
@sijiayam What URL should the "An official website of the <Parent agency>" link to?  On the USWDS website, I see that theirs goes to the GSA site, but I don't think CiviForm has a parent agency like that.

**Comment by sijiayam** [comment]
@melanie-exygy @shreyachatterjee00 Here are my suggestions below. I would want to confirm with product these requirements and changes before proceeding.

For the Civic Entity website URL:
- I think we would need to create a new admin field on the settings page, perhaps `CIVIC_ENTITY_WEBSITE`
- We can use the current field `WHITELABEL_CIVIC_ENTITY_FULL_NAME` for the display

For the more informations link:
- We can use the current field `COMMON_INTAKE_MORE_RESOURCES_LINK_HREF`
- The display could use `COMMON_INTAKE_MORE_RESOURCES_LINK_TEXT`
- I would suggest updating the description for these two admin fields as well as their name

**Comment by melanie-exygy** [comment]
> [@melanie-exygy](https://github.com/melanie-exygy) [@shreyachatterjee00](https://github.com/shreyachatterjee00) Here are my suggestions below. I would want to confirm with product these requirements and changes before proceeding.
> 
> For the Civic Entity website URL:
> 
> * I think we would need to create a new admin field on the settings page, perhaps `CIVIC_ENTITY_WEBSITE_LINK_HREF`
> * We can use the current field `WHITELABEL_CIVIC_ENTITY_FULL_NAME` for the display
> 
> For the more informations link:
> 
> * We can use the current field `COMMON_INTAKE_MORE_RESOURCES_LINK_HREF`
> * The display could use `COMMON_INTAKE_MORE_RESOURCES_LINK_TEXT`
> * I would suggest updating the description for these two admin fields as well as their name

@sijiayam Is there a difference between the civic entity website URL and the `COMMON_INTAKE_MORE_RESOURCES_LINK_HREF`?  In my mind, those are the same.  For example, "https://seattle.gov".  If we look at the USWDS example, they have a bit of a unique situation where there are essentially two parent agencies, the GSA and the U.S. Federal Government.  Our CE's don't have two different parent agencies, do they?

![Image](https://github.com/user-attachments/assets/ea405c4f-a9af-4c06-9343-da5fa1414675)

**Comment by melanie-exygy** [comment]
@lucashurt, after discussing with our UX designer, we've decided to create a separate follow-up issue for the link in the "An official website of the <parent agency>" phrase.  That issue is #9750.  In this current issue that you're working on, you can leave out the link there and just continue using whatever we were using before, so that it says:  "An official website of the City of TestCity" in the dev environment.
