### ISSUE TITLE
Mocks for "My Applications" section

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7988]
# Design updates
#### My Applications - houses all complete + in progress applications at top of program index page
-  [ ] Section starts with "My applications" header 
   -   This means that there will only ever be one or two sections on the homepage: just "Available Programs and Services" or that and "My Applications."
   - [ ] Remove displaying # applications within this section
- [ ] There are three possible tags that applications will have in that section:
    - [ ] 1. Not yet submitted" (yellow)- shows when an applicant starts, but does not submit an application (maintain our current logic)
    - [ ] 2. "Submitted on [date]" (blue) - shows when an application is submitted, but no admin status has been assigned (this might be the only status shown on some applications as not all programs teams use the status feature)
    - [ ] 3. "[Admin Status] on [date]" (blue) - shows when a program admin assigns a specific status to an application (this status could be an endless number of things)
    - [ ] We will not show eligibility badges on program cards in the "My Applications" section
   - [ ] Styles and colors changed, see designs
- [ ] Eligibility survey (common intake) also goes into "my applications" when completed
   - [ ] They will be differentiated by the color (blue) of the program card.
   
 ## Design specs
### Spacing guidelines

- Refer to Figma devmode annotations to see the spacing guidelines
- For more information about our spacing guidelines, see our writeup on spacing
    - [CiviForm spacing documentation](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=1614-7047&t=xU4eRWoQtP78C3tV-1)

### Layout guidelines
- Designs provided include mobile, desktop
  - [Desktop layout](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4702-12978&t=WJyu4u4p7ZNJuSaa-1)
  - [Mobile layout ](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4702-12978&t=WJyu4u4p7ZNJuSaa-1)

### Color guidelines
- [USWDS theme color tokens](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)
    - All colors used in the application should use one of the USWDS theme tokens
    - Dark text should use always use the theme token `ink`
    - View designs for more details

### Text styles
- All text should use the class `usa-prose` unless specified otherwise
- https://designsystem.digital.gov/components/prose/

### Components used
- [USWDS tag component](https://designsystem.digital.gov/components/tag/)
    - How we use this component
      - We use both the default, `.usa-tag` variant
      - yellow color used is `warning-light`
      - blue color used it `info-light` 
    - We use sentence case spelling on the tags rather than all caps
- [USWDS card component](https://designsystem.digital.gov/components/card/)
  - How we use this component
     - The my applications cards use the default variant with no image
     - We added the USWDS tag component 
     - Common intake submitted cards will use a background color of `primary-lighter`
# New UX
<img width="666" alt="image" src="https://github.com/user-attachments/assets/a1afda36-e049-47bc-b10c-57fcf6742a40">

# Old UX
![My Applications section](https://github.com/civiform/civiform/assets/23390490/77569361-3f48-429c-af38-50434de2755a)

**Comment by sijiayam** [comment]
@melanie-exygy I am going to add a copy of this into the #8724 issue and close this design issue.
