### ISSUE TITLE
Behavior for "Save and Finish Later"

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8523]
# Expected behavior

- [x] Change text to “Review and exit”. (https://github.com/civiform/civiform/issues/8641)
- [x] When clicked, navigate user to review page
- [x] If the input is invalid, show the error modal

# To reproduce

1. Use CiviForm as applicant
1. Start an application with multiple questions
1. Start filling out the first page of the application (see question below)
1. Click "Save and Finish Later"

[Mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2377-8313&m=dev)

# Question

What should happen in each case?
* All inputs are valid
* Some inputs are invalid
* No questions have been answered

**Comment by ssandbekkhaug** [comment]
Comment from Sijia:

- [ ] Change text to “Review and exit”.
- [ ] When clicked, navigate user to review page
- [ ] If the input is invalid, show the error modal
