### ISSUE TITLE
Change string for "Save and finish application later" Link

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8641]
# Problem
When the user is filling out an application, they might want to go back to the review page.

# Done when

- [x] A new string has been added to the Messages file
- [x] The block edit page shows a link that says "Review and exit" instead of "Save and finish application later"
- [x] Tests have been updated, including the generated test screenshots

# Notes
* [Code location](https://github.com/civiform/civiform/blob/d29bac8dc3692c4cb3e770bace5996bbc1176a16/server/app/views/applicant/ApplicantProgramBlockEditTemplate.html#L63)
* [How to add and edit strings](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29)
* [How to run browser tests](https://github.com/civiform/civiform/wiki/Common-CLI-Commands#running-browser-tests)
* For this task, don't change the link's href or any other behavior

**Comment by asnaassalam** [comment]
Hi,

I would like to work on this issue. Here’s my plan:

1. **Update the `messages` File:**
   - Add a new string entry with the key `button.reviewAndExit.v2` and the value `Review and exit`.

2. **Update the HTML Template:**
   - Modify the HTML to use the new string key `button.reviewAndExit.v2` for the button text.

Can I proceed with these changes? Please let me know if there are any specific guidelines or additional steps I should follow.

Thank you!

**Comment by AkshatRamanathan** [comment]
> Hi,
> 
> I would like to work on this issue. Here’s my plan:
> 
> 1. **Update the `messages` File:**
>    
>    * Add a new string entry with the key `button.reviewAndExit.v2` and the value `Review and exit`.
> 2. **Update the HTML Template:**
>    
>    * Modify the HTML to use the new string key `button.reviewAndExit.v2` for the button text.
> 
> Can I proceed with these changes? Please let me know if there are any specific guidelines or additional steps I should follow.
> 
> Thank you!

Let me know if it doesn't work. I would like to take it up as well if possible.

**Comment by asnaassalam** [comment]
> > Hi,
> > I would like to work on this issue. Here’s my plan:
> > 
> > 1. **Update the `messages` File:**
> >    
> >    * Add a new string entry with the key `button.reviewAndExit.v2` and the value `Review and exit`.
> > 2. **Update the HTML Template:**
> >    
> >    * Modify the HTML to use the new string key `button.reviewAndExit.v2` for the button text.
> > 
> > Can I proceed with these changes? Please let me know if there are any specific guidelines or additional steps I should follow.
> > Thank you!
> 
> Let me know if it doesn't work. I would like to take it up as well if possible.

You can work on it.

**Comment by ssandbekkhaug** [comment]
Hi folks, thank you for your interest in contributing to CiviForm. I originally intended this issue to be for a new student contributor from Open Austin. So, please do not send a PR for this issue.

If you're interested in contributing to CiviForm, can you contact Exygy at https://civiform.us/contact/ before starting?

**Comment by ssandbekkhaug** [comment]
@Erikang20 This will be an easy intro ticket to exercise the CiviForm development workflow

**Comment by Erikang20** [comment]
@ssandbekkhaug  I'll take this one! :)
