### ISSUE TITLE
Remove navigation to Program Review page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8662]
# Description

Remove links to this page when the user clicks "Apply" from the homepage and when the user clicks "Review" from the form.

Code location: [ApplicantProgramSummaryTemplate.html](https://github.com/civiform/civiform/blob/main/server/app/views/applicant/ApplicantProgramSummaryTemplate.html)

# Screenshot

<img width="1552" alt="review" src="https://github.com/user-attachments/assets/5ad29c76-fa8c-4427-b988-789826b660b6">

# Done when

- [ ] #8642 is fixed
- [ ] It is not possible to navigate to the program review page
- [ ] All references to the program review page have been deleted
- [ ] Users cannot use the `/review` url to access this page

**Comment by ssandbekkhaug** [comment]
We're going to keep the review page (though it will have some significant changes). See #7935
