### ISSUE TITLE
[North Star Applicant UI] Style "My Applications" section

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#8724]
#### Describe the solution presented in this issue.
- Style the "My applications" section according to the mocks.
- Remove eligibility badges from the cards in the "My applications" section

#### Link to Figma mocks:
  - [mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2036-12554&m=dev)

#### Add screenshot of relevant mocks for this issue here: 
![Image](https://github.com/user-attachments/assets/1e56f795-c55c-4d48-a0cf-b99dadb47d59)

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] Cards in the "My Applications" section match the mocks.
- [ ] The common intake form (AKA "Benefits Finder"), when completed, shows up in "My applications", with different styles than the other cards.
- [ ] Status badges match the mocks
- [ ] Eligibility badges have been removed from the cards in the "My applications" section

# Design updates
#### My Applications - houses all complete + in progress applications at top of program index page
-  [x] Section starts with "My applications" header 
   -   This means that there will only ever be one or two sections on the homepage: just "Available Programs and Services" or that and "My Applications."
   - [x] Remove displaying # applications within this section
- [ ] There are three possible tags that applications will have in that section:
    - [x] 1. Not yet submitted" (yellow)- shows when an applicant starts, but does not submit an application (maintain our current logic)
    - [x] 2. "Submitted on [date]" (blue) - shows when an application is submitted, but no admin status has been assigned (this might be the only status shown on some applications as not all programs teams use the status feature)
    - [ ] #9165
    - [x] We will not show eligibility badges on program cards in the "My Applications" section
   - [x] Styles and colors changed, see designs
- [ ] Eligibility survey (common intake) also goes into "my applications" when completed
   - [ ] They will be differentiated by the color (blue) of the program card.
   
 ## Design specs
### Spacing guidelines

- Refer to Figma devmode annotations to see the spacing guidelines
- For more information about our spacing guidelines, see our writeup on spacing
    - [CiviForm spacing documentation](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=1614-7047&t=xU4eRWoQtP78C3tV-1)

### Layout guidelines
- Designs provided include mobile, desktop
  - [Desktop layout](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4702-12978&t=WJyu4u4p7ZNJuSaa-1)
  - [Mobile layout ](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4702-12978&t=WJyu4u4p7ZNJuSaa-1)

### Color guidelines
- [USWDS theme color tokens](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)
    - All colors used in the application should use one of the USWDS theme tokens
    - Dark text should use always use the theme token `ink`
    - View designs for more details

### Text styles
- All text should use the class `usa-prose` unless specified otherwise
- https://designsystem.digital.gov/components/prose/

### Components used
- [USWDS tag component](https://designsystem.digital.gov/components/tag/)
    - How we use this component
      - We use both the default, `.usa-tag` variant
      - yellow color used is `warning-light`
      - blue color used it `info-light` 
    - We use sentence case spelling on the tags rather than all caps
- [USWDS card component](https://designsystem.digital.gov/components/card/)
  - How we use this component
     - The my applications cards use the default variant with no image
     - We added the USWDS tag component 
     - Common intake submitted cards will use a background color of `primary-lighter`
# New UX
![Image](https://github.com/user-attachments/assets/f1154e22-5b13-47ee-b2d7-bef82416479d)

# Old UX
![My Applications section](https://github.com/civiform/civiform/assets/23390490/77569361-3f48-429c-af38-50434de2755a)

**Comment by isabelcshaw** [comment]
After some discussion, here is the expected behavior of this section: (@sijiayam pls correct/add what I miss!)

**Comment by isabelcshaw** [comment]
@sijiayam realizing that bc admin statuses can be anything, we should probably set a limit on the tag. I don't think they are likely to create a status longer than two or three words, so I'm ok with a character limit here

**Comment by sijiayam** [comment]
@isabelcshaw Re the character limit. Do we want to enforce it on the front-end or the back-end (in the admin UI).

I think best practice would be to enforce it in the admin UI itself so admins are aware of the limit, that would mean we need to update the functionality on the admin side. Alternatively we could have a display limit...

@melanie-exygy Any estimate on which approach would take longer/if there is a significant difference?

**Comment by isabelcshaw** [comment]
@sijiayam great point! @melanie-exygy do you have a sense of the LOE required to add a character limit to this field for admins? Given that it's really just protecting an edge case here, I would even be ok not indicating the character limit in the UI for admins if that saved any real time. 

<img width="779" alt="Screenshot 2024-10-23 at 1 00 18 PM" src="https://github.com/user-attachments/assets/0f376b39-a599-4888-8abb-b830a03dbfbf">

**Comment by melanie-exygy** [comment]
> @sijiayam great point! @melanie-exygy do you have a sense of the LOE required to add a character limit to this field for admins? Given that it's really just protecting an edge case here, I would even be ok not indicating the character limit in the UI for admins if that saved any real time.
> 
@sijiayam @isabelcshaw, we often truncate long text.  For example, we truncate the program description on the program cards if it's too long.  Also, even if I put a character limit on the admin side, that won't take care of any existing long statuses.  I vote that we truncate the status on the "My Applications" card and leave status length as-is so that the full status can be displayed in emails and anywhere else.

**Comment by melanie-exygy** [comment]
> > @sijiayam great point! @melanie-exygy do you have a sense of the LOE required to add a character limit to this field for admins? Given that it's really just protecting an edge case here, I would even be ok not indicating the character limit in the UI for admins if that saved any real time.
> 
> @sijiayam @isabelcshaw, we often truncate long text. For example, we truncate the program description on the program cards if it's too long. Also, even if I put a character limit on the admin side, that won't take care of any existing long statuses. I vote that we truncate the status on the "My Applications" card and leave status length as-is so that the full status can be displayed in emails and anywhere else.

Maybe the best solution is to do both.  That way, we prevent any new statuses from being long and needing to be truncated.  I could easily put a character limit on the admin side if I don't have to worry about a validation error message.  It would just be a tiny change.  The experience for the admin would be that they can't type any more characters once they've reached the limit.  If you'd like me to do that, just let me know what the limit should be.

**Comment by sijiayam** [comment]
@melanie-exygy Could we concat on the front-end for now and create a separate issue for M3.5 that introduces a new admin character limit?

I think around a 30 character limit length would be ideal here for the card size, especially if we append a date to it.

**Comment by melanie-exygy** [comment]
> @melanie-exygy Could we concat on the front-end for now and create a separate issue for M3.5 that introduces a new admin character limit?
> 
> I think around a 30 character limit length would be ideal here for the card size, especially if we append a date to it.

That sounds fine to me, but I think that we should continue truncating even after adding the limit, for any existing long statuses.  Also, once we put a limit, do you think it's fine for admins that are editing a long status to have to make it shorter (like in the example I gave above)?

**Comment by sijiayam** [comment]
> That sounds fine to me, but I think that we should continue truncating even after adding the limit, for any existing long statuses. Also, once we put a limit, do you think it's fine for admins that are editing a long status to have to make it shorter (like in the example I gave above)?

1. Yep I think we can continue trncating
2. I think this is alright @isabelcshaw do you have any opinions/have you heard of any use cases where this could be an issue?

**Comment by ssandbekkhaug** [comment]
The tags are being implemented here: https://github.com/civiform/civiform/pull/9144
