### ISSUE TITLE
Create basic functionality for North Star "application review" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8792]
# Description
Mocks in https://github.com/civiform/civiform/issues/7935

# Done when

- [x] When the user has filled out an application and they click "Continue", the user sees the "application review" page
- [x] The application review page has the following sections:
    - [x] Page header (title and description fragment)
    - [x] Progress bar (#8847)
    - [x] Action buttons
        - [x] Clicking the submit button submits the application

Out of scope of this issue:
- [ ] Showing all data properly
- [ ] Styling
- [ ] "Edit" button https://github.com/civiform/civiform/issues/8780
- [ ] "Save and exit" button https://github.com/civiform/civiform/issues/8779

**Comment by ssandbekkhaug** [comment]
I'll start on this issue in the sprint that starts today (Oct 7). I expect to only get partially through it and/or hand it off to someone else.
