### ISSUE TITLE
Styling for North Star "application review" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8794]
# Description
Add styling to the North Star "application review" page

* Mocks: https://github.com/civiform/civiform/issues/7935
* Basic functionality: https://github.com/civiform/civiform/issues/8792

# Done when

- [ ] North Star "application review" page is styled according to the mocks

# Design updates
#### Page layout:
- Page header
- Progress bar
- Main content, review sections by screens
- Action buttons

#### Page header updates
- [x] Update text and color styles
#### Page header updates
- [x] Should follow the same format as all other form pages
#### Main content
- [x] Review sections are laid out in order by screen
- [x] Each screen section has:
  - [x] Screen title
  - [x] #8780
  - [x] Question titles and responses are shown in order of question
#### Action buttons
- [ ] Save and exit
  - [ ] If an applicant is logged in, they will redirected to a page with a success message
  - [ ] #8779
- [x] Submit application
  - [x] If an applicant submits their application, they will be redirected to the confirmation screen

### Spacing guidelines

- Refer to Figma devmode annotations to see the spacing guidelines
- CiviForm spacing documentation
- For more information about our spacing guidelines, see our writeup on spacing

### Layout guidelines
- [Layout guidelines](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4287-23350&t=XCIBJDfrfoPaX0e8-1)
- Designs include
  - [ ] [Mobile layout](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3707-15814&t=XCIBJDfrfoPaX0e8-1)
  - [ ] [Desktop layout](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2468-5090&t=XCIBJDfrfoPaX0e8-1)

### Color guidelines
- [USWDS theme color tokens](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)
  - All colors used in the application should use one of the USWDS theme tokens
  - Dark text should use always use the theme token `ink`
  - View designs for more details

### Text styles
- All text should use the class `usa-prose` unless specified otherwise 
- https://designsystem.digital.gov/components/prose/

### USWDS components used

- [USWDS step indicator component](https://designsystem.digital.gov/components/step-indicator/) 
    - Guidance on the how to use the component
    - We are using the variant `.usa-step-indicator--no-labels`
    - See other North Star form page for styles implemented
- [USWDS button](https://designsystem.digital.gov/components/button/)
    - We are using the default and `outline` variant
    - See guidance in devmode

### Accessibility
- TBD

### Preview mock
<img width="307" alt="image" src="https://github.com/user-attachments/assets/604497d4-4f99-400d-b87f-8db451253819">

**Comment by ssandbekkhaug** [comment]
Blocked by https://github.com/civiform/civiform/issues/7935 and https://github.com/civiform/civiform/issues/8792

**Comment by ssandbekkhaug** [comment]
Ready for UX review

**Comment by sijiayam** [comment]
Design QA approved, open issue related to header structure accessibility still open https://github.com/civiform/civiform/issues/9048
