### ISSUE TITLE
Support progress bar on summary page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8847]
# Summary

Add the summary page as the last step in the progress bar.

# Problem

Today, the progress bar displays "X of Y", where:
- X is the current block index
- Y is the total number of blocks

On the "Application Summary" page ([mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23883&m=dev)), the application summary page is represented as another step in the progress bar.

## Expected behavior
In an application with 2 real blocks:

- Block 1 shows as "1 of 3"
- Block 2 shows as "2 of 3"
- The review page shows as "3 of 3"

## Actual behavior
- Block 1 shows as "1 of 2"
- Block 2 shows as "2 of 2"
- The review page does not show anything

## Done when

- [x] Strings are updated ("X of Y")
- [x] Block names are corrected
- [x] The appearance of the progress bar (number of segments, colors, etc) matches USWDS standards
- [x] The summary page is the last step in the progress bar
- [x] Progress bar fragment has [aria attributes](https://github.com/civiform/civiform/pull/8848#discussion_r1799859911)
