### ISSUE TITLE
Update program description field to use new short description field

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#9019]
The field that the program description uses will be updated in the #8243 work. We need to update the field to use the shorter description field that will be added.

Done when:

- [ ] Program description field uses the new short description field
- [ ] Application flows display the short description text, and falls back on the long description if the short description is empty
  - [ ] Long description text will be truncated to 150 characters with an ellipsis `...`

![](https://files.slack.com/files-pri/T01Q6PJQAES-F07TE5FP0Q2/image.png)

**Comment by rockycodes** [comment]
@sijiayam can we close this issue as a duplicate of https://github.com/orgs/civiform/projects/1/views/94?pane=issue&itemId=85441842&issue=civiform%7Cciviform%7C9089?
