### ISSUE TITLE
[Program Overview Page] Add new application steps fields to program create/edit page

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#9086]
Allow admins to add up to five application steps describing the application process.

Acceptance criteria:

- [x]  The program create/edit page includes space to add up titles and descriptions for up to five application steps
- [x] These fields are grouped together in a new "How to apply" section that is below the "Program overview" section
- [x] The first application step is required
- [x] When the admin saves the program, the application steps are saved to the `application_steps` column on the `programs` table as an array of application steps that includes json representation of both the title and description as `LocalizedStrings`
- [x] If an admin attempts to save the program without filling out the first application step, they are shown an error saying that the first application step is required
- [x] If an admin attempts to save the program with an application step that is missing either the title or description, they are shown an error saying that application steps must have both a title and a description
- [x] If an admin leaves a step in the middle blank, the other steps are condensed so there is no blank step in the middle

See [the TDD](https://docs.google.com/document/d/1rP4kqltv122Wfp9-maJlvm5rzFkFcWrCt5w0lKRoZEs/edit?tab=t.0#heading=h.rto1cqcwpkdl) for more information about the implementation plan and sample code

**Comment by rockycodes** [comment]
Blocked by #9085
