### ISSUE TITLE
[Program Overview Page] Handle translations for short description and application steps

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#9087]
Allow admin to enter translations for new short description and application steps field via the existing translation flow.

Acceptance criteria:
- [ ] Admin have space to enter translations for short description and application steps on the existing translations pages
- [ ] Existing translations show in the appropriate fields
- [ ] The English text is shown on the page
- [ ] When the admin saves the translations, the `localized_short_description` and `application_steps` columns on the programs table will be updated with the new translations

See [the TDD](https://docs.google.com/document/d/1rP4kqltv122Wfp9-maJlvm5rzFkFcWrCt5w0lKRoZEs/edit?tab=t.0#heading=h.skfjmtw57kvt) for more information and implementation details

**Comment by rockycodes** [comment]
Blocked by #9086
