### ISSUE TITLE
[Program Overview Page] Build out new applicant facing program overview page

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#9088]
Implement new applicant facing page that provides an overview of the program.

Acceptance criteria:
- [x] The url for the program overview page is `programs/:programSlug`
- [x] Applicants see a page that renders information about the program and visually matches the [mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2741-5764&m=dev) as closely as possible (the correct mock is the the one that says "Child care assistance program" at the top)
- [x] This page includes all fields input by the admin, which can include:
- Title, long description 
- Button that takes the resident to the start of the application 
- Eligibility banner (already exists, but design is updated) 
- Steps on how to apply (whichever steps admin decides to input for that program)
- Option to create an account or login
- [x] Long description is rendered with markdown (defer to #9531 )
- [x] If the long description does not exist for the program, the short description is rendered
- [x] The page uses the [USWDS process list component](https://designsystem.digital.gov/components/process-list/) to render application steps, and other USWDS components as indicated by the design.  The steps descriptions are rendered with markdown.
- [x] When a user clicks the "Start your application" button at the bottom of the screen, they are taken to the first page of the application
- [x] When a user clicks the "Log in" button they are taken to the log in screen
- [x] When a user clicks "view and apply", they are NOT shown the "Create an account or sign in" modal. If they go to the program overview page and then click "start application", they also are NOT show that modal.
- [x] #9455

See [the TDD](https://docs.google.com/document/d/1rP4kqltv122Wfp9-maJlvm5rzFkFcWrCt5w0lKRoZEs/edit?tab=t.0) for more information and implementation details

Note: The "More information" section is not being implemented at this time.
Also, the program external link will not be included.  Rather, we will let admins add links in the long description.

**Comment by rockycodes** [comment]
Note: Work on this can begin in parallel with the admin UI using dummy data. Once #9085 and #9086 are completed, we can swap in the values pulled from the db.

**Comment by shreyachatterjee00** [comment]
Note: made a decision to show our "Create an account or sign in" modal when the user clicks "start an application" from the program overview page, rather than when the user clicks "View and apply" (which is the current behavior before program overview). 
![image](https://github.com/user-attachments/assets/5392a1e1-745e-4d05-abe5-4b69e5721d66)

**Comment by sijiayam** [comment]
Renoting the feature change here: this modal should not be shown before a user applies to a program. It will be displayed after an applicant submits their application and when they navigate away. 

cc @shreyachatterjee00 @melanie-exygy

**Comment by melanie-exygy** [comment]
> Renoting the feature change here: this modal should not be shown before a user applies to a program.
> 
> * A modal will be displayed after an applicant submits their application and when they navigate away.
> * A modal will be displayed mid application if a user clicks on "save and exit" , see [Save and exit on the review page. If an applicant is not logged in, they will be prompted to create an account #8779](https://github.com/civiform/civiform/issues/8779)
> 
> cc [@shreyachatterjee00](https://github.com/shreyachatterjee00) [@melanie-exygy](https://github.com/melanie-exygy)

@shreyachatterjee00 @sijiayam Did we then decide not to display the "Create an account" modal when the user clicks "start an application" from the program overview page (as Shreya described above)?  That's what I understand from "this modal should not be shown before a user applies to a program".  Just want to make sure I understand the final decision correctly.

**Comment by sijiayam** [comment]
We should use the `slim alert` variant for the eligibility message. https://designsystem.digital.gov/components/alert/

**Comment by shreyachatterjee00** [comment]
@melanie-exygy yes, that's correct (and we already show the create an account modal on the program overview itself.)

**Comment by melanie-exygy** [comment]
@sijiayam @shreyachatterjee00, should this alert show if the user is already logged in?  

![Image](https://github.com/user-attachments/assets/e14da8cc-7d34-442c-a1c4-22a0e34aa3a9)

What should happen when the user clicks on "Start application with an account" here?  We decided (see above comments) not to display the "Create an account" modal when the user clicks "start an application" from the program overview page, but it seems strange to me that the alert says "Create an account to save your application information" and then doesn't direct them to creating an account.
