### ISSUE TITLE
[Program Overview Page] Update program cards with new info

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#9089]
Add the short description to program cards and implement logic to navigate to program overview page when the user clicks the "View and apply" button.

Acceptance criteria:
- [x] The short description is rendered on the program card
- [x] If the short description is not available, the long description is stripped of markdown, truncated to 100 characters, appended with "..." and rendered in its place
- [x] The "View and apply" button navigates to the program overview page (`programs/:programSlug`)
- [x] The program overview page opens in the same tab as the homepage

See [the TDD](https://docs.google.com/document/d/1rP4kqltv122Wfp9-maJlvm5rzFkFcWrCt5w0lKRoZEs/edit?tab=t.0#heading=h.ou6qc4sdmfs7) for more information and implementation details

Note: Stripping the markdown off of the long description will require some thought. We might not want to strip all markdown, eg. we might want to leave A tags so they still render as links. Check with product/design on this.

**Comment by rockycodes** [comment]
Blocked by #8157
