### ISSUE TITLE
Change the program name class to .cf-applicant-cif-eligible-program-name.

### ISSUE THREAD

**Issue by orwant** [civiform/civiform#9304]
### Checklist (remove this section after completion): 
- [X] Add the correct epic label to the 'epic' category 
- [X] Add the correct status to the 'status' category
- [X] Complete the info below

#### Describe the solution presented in this issue.

In North Star, change the class of the program name to `.cf-applicant-cif-eligible-program-name`.

Background:

Jon's comment in `expectCommonIntakeConfirmationPageNorthStar()`:

>   // Prior to North Star, the program name was rendered with
>   // class='.cf-applicant-cif-eligible-program-name'. In North Star,
>   // it's '.cf-prose-h4' instead. Working as intended?

Danielle's response:

> Good call out / question! We can update the class in the template and update the locator here to something more descriptive: https://github.com/civiform/civiform/blob/35bbff23f6f9d6729fb045c454b24e0b814d219a/server/app/views/applicant/ApplicantUpsellTemplate.html. I imagine it was just cause there wasn't a test added for this yet that nobody added a more helpful class name.

#### Done when:
What criteria need to be met for the issue to be finished? 
- [] In North Star, the class for the program name is `.cf-applicant-cif-eligible-program-name`.
- [] `expectCommonIntakeConfirmationPageNorthStar()` is updated to look for that class.
