### ISSUE TITLE
Remove unneeded screenshots / screenshot tests for northstar_application_navigation_common_intake_test

### ISSUE THREAD

**Issue by orwant** [civiform/civiform#9306]
### Checklist (remove this section after completion): 
- [X] Add the correct epic label to the 'epic' category 
- [X] Add the correct status to the 'status' category
- [X] Complete the info below

#### Describe the solution presented in this issue.

- Remove unneeded screenshots from browser-test/image_snapshots/northstar_application_navigation_common_intake_test/.
- Remove screenshot validations from browser-test/src/applicant/navigation/northstar_application_navigation_common_intake.test.ts.

#### Additional Context

Danielle, on https://github.com/civiform/civiform/pull/9300:

> This test file (as it was written) has a lot of screenshot tests, which makes the test run quite slow. Since we have the "expectCommonIntakeConfirmationPageNorthStar" asserts in most of these, we can remove the screenshots that feel duplicative. Out of scope for the migration, but would be a nice cleanup opportunity. See note in https://github.com/civiform/civiform/wiki/Testing#how-to-add-new-screenshots for more information

Add any other context, link related issues, etc. 

#### Done when:
- [ ] Duplicative screenshots are removed.
- [ ] The tests for those screenshots are removed.
