### ISSUE TITLE
Multiple file upload "Remove file" links need more precise label and should be buttons rather than links

### ISSUE THREAD

**Issue by orwant** [civiform/civiform#9467]
### Checklist (remove this section after completion): 
- [X] Add the correct epic label to the 'epic' category 
- [ ] Add the correct status to the 'status' category
- [X] Complete the info below

#### Describe the solution presented in this issue.

Discovered when porting browser-test/src/applicant/questions/file.test.ts to North Star, the test "remove button has correct aria-labelled by" fails because there is no aria-labelledby class on the "Remove File" link.

For the test to pass as is, there needs to be an aria-labelledby class present in the link. 

#### Additional Context

Legacy HTML:

`<a __playwright_target__="call@400" href="link:///programs/2/blocks/1/removeFile/applicant-4%2Fprogram-2%2Fblock-1%2Ffile-upload.png/false" aria-labelledby="uploaded-file-1" class="text-blue-600 hover:text-blue-500 underline ml-2 shrink-0">Remove file</a>`

North Star HTML:

`<a __playwright_target__="call@394" href="link:///programs/3/blocks/1/removeFile/applicant-6%2Fprogram-3%2Fblock-1%2Ffile-upload.png/false" style="outline: rgb(0, 106, 177) solid 2px; background-color: rgba(111, 168, 220, 0.498);">Remove file</a>
`
#### Done when:

Either Sijia says we don't care about the aria-labelledby class in North Star, or someone adds it to North Star.

**Comment by melanie-exygy** [comment]
The links do have labels, which is the text between the opening and closing anchor tags.  So, the problem here isn't that the link lacks an `aria-labelledby`.  The problem is that the link label is duplicate when there are multiple files with the "Remove file" link.  We should modify the link text or the aria label to include the name of the file.  For example: "Remove puppy.jpg file".

Also, semantically these should be buttons, not links.  The purpose of a link would be to take the user to a different location, whereas the purpose of a button is for the user to take action.
